# Generated by Django 5.2 on 2025-05-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myroomieApp', '0004_remove_profile_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roommember',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
