# Generated by Django 5.2 on 2025-05-22 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myroomieApp', '0006_room_is_private_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='created',
            new_name='created_at',
        ),
    ]
